apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: composer-ai-rhsso

patches:
  - target:
      kind: Subscription
      name: rhsso-operator
    path: patch-channel.yaml
