kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-oidc-role
  namespace: composer-ai-rhsso
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - secrets
