apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: composer-ai-config
  namespace: composer-ai-gitops
  labels:
    gitops.ownedBy: cluster-config
    tenant: composer-ai
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: https://github.com/redhat-composer-ai/appOfApps.git
      path: appOfApps
      targetRevision: v2.2.0
      helm:
        parameters:
          - name: namespacePrefix
            value: composer-ai-
          - name: clusterDomain
            value: ${SUB_DOMAIN}
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/source/repoURL
        - /spec/source/targetRevision
