apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: composer-ai-config
  namespace: composer-ai-gitops
spec:
  sources:
    - repoURL: https://github.com/lcoronad/appOfApps.git
      path: appOfApps
      targetRevision: main
      helm:
        parameters:
          - name: namespacePrefix
            value: composer-ai-
          - name: clusterDomain
            value: ${SUB_DOMAIN}
        valueFiles:
          - $values/appOfApps/values-lab.yaml
    - repoURL: 'https://github.com/lcoronad/appOfApps.git'
      targetRevision: main
      ref: values
