kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-setup-role
rules:
  - verbs:
      - get
      - create
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - get
      - delete
    apiGroups:
      - ''
    resources:
      - pods
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-setup-clusterrole
rules:
  - verbs:
      - get
    apiGroups:
      - config.openshift.io
    resources:
      - ingresses
